### ISSUE TITLE
Custom firmware

### ISSUE THREAD

**Issue by matiaspl** [BertoldVdb/ms-tools#1]
I came here looking to fix the slight discoloration/video level/ mismatch on the MS2109. I haven't come across any datasheet of the chip online, but it seems you gained a lot of knowledge during your reverse engineering efforts. Will you be sharing your source code of your custom made MS2106 board anytime soon? I'm hoping to find something that may point me to the right direction.

**Comment by animaone** [comment]
@matiaspl the video-to-usb card uses uvc(Universal Video Control) as a default. Maybe you can change color configs with a good uvc software.
I have done some reverse-engineering in the usb-to-vga card MS6021(aka MS2190). I've found some registers(similar to ms2109 TVD registers?)
Also the code from @BertoldVdb have some tips on patching the device's assembly code. I've done something similar, but I didn't understood how the RAM mapping could be changing memory banks(looks like it is probabilistically obfuscated?)
It is a work-in-progress, I still will organize it. Take a look in the Java files, they may help: https://github.com/animaone/macrosilicon_reverse_engineering_journey
