### ISSUE TITLE
There's a windows tool capable of doing the vid&pid modifications mentioned here (MS21XX&91XXDownloadTool_1.7.0_BUILD20221024): https://twitter.com/aaaarrrriaaannn/status/1678837967756902404?t=u_ezQ04APCLDtlgRT5tYlA&s=19

### ISSUE THREAD

**Issue by parbzip** [BertoldVdb/ms-tools#11]
There's a windows tool capable of doing the vid&pid modifications mentioned here (MS21XX&91XXDownloadTool_1.7.0_BUILD20221024): https://twitter.com/aaaarrrriaaannn/status/1678837967756902404?t=u_ezQ04APCLDtlgRT5tYlA&s=19

_Originally posted by @matiaspl in https://github.com/BertoldVdb/ms-tools/issues/9#issuecomment-1631819412_
            
Is it convenient to give the tool download address, thank you

**Comment by tablesturn** [comment]
@ariankordi Can you tell us which device driver you installed to use the .exe?

I am trying to get the firmware of a MS9122 (VID345F PID9132, just like the MS9132) by using the WinUSBDisplay_Windows_V3.1.5.75 driver but the software can't connect to the device.

I also tried a generic LibUSB driver which didn't work, too.
Maybe the .exe checks if it actually is a MS9132, or I am just using the wrong Windows driver.

**Comment by tablesturn** [comment]
@ariankordi Never mind, the WinUSBDisplay_Windows_V3.1.5.75 driver works after (partially) patching my MS9132 to be a MS2106 (which seems to have broken some things haha) using the ms-tools cli, modified to assume that the device is a MS2106.
