### ISSUE TITLE
MS1858(cvbsTOhdmi)

### ISSUE THREAD

**Issue by Raduq91** [BertoldVdb/ms-tools#4]
On the page macrosilicon page it says it can be controlled trough external microcontroller with I2C
The internet is absolutely full of these cheap av2hdmi but all output at 60hz.I have a pal console and I want out at 50hz.
There are more expensive ones 60$-100$.

Can you figure out if you can configure it to output at 50hz?
It says it has "frame rate conversion", maybe it can be disabled.It says it has OSD, maybe it can be accessed. 

this is the unit(I bought mine from local shop):
https://www.dropbox.com/s/1t8gwbczl6c0fk6/FRUJSA7KZ7C4DZG.png?dl=0

Here is the link to the chip on macrosilicon site:
http://en.macrosilicon.com/info.asp?base_id=2&third_id=71

low rez chip pinout:
https://www.dropbox.com/s/ctneyk6oiid6cju/9a51f749a49817ec4d345579f50dcbe9.png?dl=0

m1858 datasheet(no info on how to configure i2c):
https://www.dropbox.com/s/7q5n10tczddaosm/MS1858%20External%20Datasheet%20V1_0_nowatermark.pdf?dl=0

m1820 datasheet(different chip), it has this bit:
Host Interface
MS1820 registers are accessed by a 2-wire serial bus interface. It operates as a slave device and follows I2C
standard. The data transfer rate up to 400Kbit/s.
Table 1. I2C Slave Address
I2C Slave Addresses
Pin SCLSA Value Read Write
SCLSA = 0 0xB3 0xB2
SCLSA =1 0xBB 0xBA
https://www.dropbox.com/s/c51ubr9nmkm9fg4/MS1820-MacroSilicon.pdf?dl=0

**Comment by BertoldVdb** [comment]
Maybe try to read out the EEPROM attached to the chip and check what is in it (likely either 8051 code or some register settings).

**Comment by Raduq91** [comment]
> Maybe try to read out the EEPROM attached to the chip and check what is in it (likely either 8051 code or some register settings).

24c02 8 pin chip top right.Maybe that is the edid for the input?
https://www.dropbox.com/s/1jar4
![24c02av2hdmi_](https://user-images.githubusercontent.com/31180871/203917694-aae1dc5c-e438-4241-9d20-008ddb790581.png)
b1n0ber1bt/24c02av2hdmi.bin?dl=0


After opened with Deltacast E edid, errors appeared with continue anyway and fix and saved file:
https://www.dropbox.com/s/iu2n25rbr9pv9sy/24c02av2hdmi_deltafixed.bin?dl=0
![Untitled](https://user-images.githubusercontent.com/31180871/203917591-d898774a-b189-4669-a4b4-b87811e08d1c.png)

**Comment by BertoldVdb** [comment]
It is clearly not an EDID, it doesn't start with '00 FF FF FF FF FF FF 00'. I fear it will be a lot of trial and error now to figure out which register does what.
