### ISSUE TITLE
Discusion

### ISSUE THREAD

**Issue by robots** [BertoldVdb/ms-tools#5]
Hi,
I have just bought ms2109 device and found your repo. 

Did you do some research around the encoder/hdmi capturer of this device ? Or are you just using it as general purpose mcu ?

Do you plan to release the custom firmware ?

Thanks :-)

**Comment by BertoldVdb** [comment]
I mostly looked into the TV decoder on the MS2106 to be able to disable AGC and switch which input is used. The MS2109 I didn't investigate.
