### ISSUE TITLE
Additional sources?

### ISSUE THREAD

**Issue by carrotIndustries** [BertoldVdb/ms-tools#6]
First of all thank you for the research you did! Using the MS2109's I²C interface has made an upcoming project much more practical.

I was wondering, how did you figure out the HID reports to send and the other details since there appears to be no publicly available documentation for this chip? Is there some software that uses these features that you reverse engineered?

**Comment by BertoldVdb** [comment]
Hello,

I did this purely based on the firmware itself. I needed a way to program the EEPROM on the board via USB.

Presumably there is a PC software that can do this (how do they program the devices in the factory otherwise?) but I never saw it.

Sincerely,
Bertold

**Comment by carrotIndustries** [comment]
> I did this purely based on the firmware itself. I needed a way to program the EEPROM on the board via USB.

Impressive, thanks again for the project!
