### ISSUE TITLE
Is it possible to expose the live mjpeg video feed on a GPIO pin?

### ISSUE THREAD

**Issue by SziluChannel** [BertoldVdb/ms-tools#8]
I'm building a custom FPV system and this seems to be a relatively easy solution to get a digital video feed from an analog camera.

**Comment by BertoldVdb** [comment]
Hello,

No, I don't think so. You would need a USB host. Most simple SoCs could do
this task though.

Can you not use one of the many low-end SoCs with video decoder and mjpeg
block? There are several in QFN or TQFP packages. If you can solder a BGA
there is even more choice.

Sincerely,
Bertold

Op ma 27 feb. 2023 17:10 schreef SziluChannel ***@***.***>:
